
/* File generated by gen_cfile.py. Should not be modified. */

#include "TaskSlave.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
INTEGER16 CAN_ACC[] =		/* Mapped at index 0x2000, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x3E8	/* 1000 */
  };
INTEGER16 GYR[] =		/* Mapped at index 0x2001, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER16 MAG[] =		/* Mapped at index 0x2002, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER16 EUL[] =		/* Mapped at index 0x2003, subindex 0x01 - 0x03 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER16 QUAT[] =		/* Mapped at index 0x2004, subindex 0x01 - 0x04 */
  {
    0x2710,	/* 10000 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
INTEGER32 CAN_BAUD = 0x7A120;		/* Mapped at index 0x2100, subindex 0x00 */
INTEGER32 NodeID = 0x8;		/* Mapped at index 0x2101, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 TaskSlave_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 TaskSlave_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 TaskSlave_iam_a_slave = 1;

TIMER_HANDLE TaskSlave_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 TaskSlave_obj1000 = 0x20192;	/* 131474 */
                    subindex TaskSlave_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 TaskSlave_obj1001 = 0x0;	/* 0 */
                    subindex TaskSlave_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1001, NULL }
                     };

/* index 0x1002 :   Manufacturer Status Register. */
                    UNS32 TaskSlave_obj1002 = 0x0;	/* 0 */
                    subindex TaskSlave_Index1002[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1002, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 TaskSlave_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex TaskSlave_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID. */
                    UNS32 TaskSlave_obj1005 = 0x0;	/* 0 */
                    subindex TaskSlave_Index1005[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1005, NULL }
                     };

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 TaskSlave_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 TaskSlave_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 TaskSlave_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 TaskSlave_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 TaskSlave_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1016[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex TaskSlave_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1016, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1016[0], NULL }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 TaskSlave_obj1017 = 0x0;	/* 0 */
                    subindex TaskSlave_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 TaskSlave_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1018_Vendor_ID = 0x700;	/* 1792 */
                    UNS32 TaskSlave_obj1018_Product_Code = 0x700;	/* 1792 */
                    UNS32 TaskSlave_obj1018_Revision_Number = 0x1;	/* 1 */
                    UNS32 TaskSlave_obj1018_Serial_Number = 0x9B939E8F;	/* 2610142863 */
                    subindex TaskSlave_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 TaskSlave_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 TaskSlave_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex TaskSlave_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1200, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1200_COB_ID_Client_to_Server_Receive_SDO, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1200_COB_ID_Server_to_Client_Transmit_SDO, NULL }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 TaskSlave_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 TaskSlave_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TaskSlave_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 TaskSlave_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex TaskSlave_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 TaskSlave_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 TaskSlave_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TaskSlave_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 TaskSlave_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex TaskSlave_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 TaskSlave_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 TaskSlave_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TaskSlave_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 TaskSlave_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex TaskSlave_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 TaskSlave_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 TaskSlave_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 TaskSlave_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 TaskSlave_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex TaskSlave_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 TaskSlave_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1600[] = 
                    {
                      0x20000110,	/* 536871184 */
                      0x20000210,	/* 536871440 */
                      0x20000310,	/* 536871696 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TaskSlave_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1600, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1600[0], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1600[1], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1600[2], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1600[3], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1600[4], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1600[5], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1600[6], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1600[7], NULL }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 TaskSlave_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1601[] = 
                    {
                      0x20010110,	/* 536936720 */
                      0x20010210,	/* 536936976 */
                      0x20010310,	/* 536937232 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TaskSlave_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1601, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1601[0], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1601[1], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1601[2], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1601[3], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1601[4], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1601[5], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1601[6], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1601[7], NULL }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 TaskSlave_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1602[] = 
                    {
                      0x20030110,	/* 537067792 */
                      0x20030210,	/* 537068048 */
                      0x20030310,	/* 537068304 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TaskSlave_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1602, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1602[0], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1602[1], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1602[2], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1602[3], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1602[4], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1602[5], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1602[6], NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1602[7], NULL }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 TaskSlave_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1603[] = 
                    {
                      0x20040110,	/* 537133328 */
                      0x20040210,	/* 537133584 */
                      0x20040310,	/* 537133840 */
                      0x20040410,	/* 537134096 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TaskSlave_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1603[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1603[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1603[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1603[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1603[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1603[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1603[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1603[7], NULL }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 TaskSlave_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 TaskSlave_obj1800_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TaskSlave_obj1800_Inhibit_Time = 0x40;	/* 64 */
                    UNS8 TaskSlave_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1800_Event_Timer = 0xA;	/* 10 */
                    UNS8 TaskSlave_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex TaskSlave_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 TaskSlave_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 TaskSlave_obj1801_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TaskSlave_obj1801_Inhibit_Time = 0x40;	/* 64 */
                    UNS8 TaskSlave_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1801_Event_Timer = 0xA;	/* 10 */
                    UNS8 TaskSlave_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex TaskSlave_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 TaskSlave_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 TaskSlave_obj1802_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 TaskSlave_obj1802_Inhibit_Time = 0x40;	/* 64 */
                    UNS8 TaskSlave_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1802_Event_Timer = 0xA;	/* 10 */
                    UNS8 TaskSlave_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex TaskSlave_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 TaskSlave_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 TaskSlave_obj1803_Transmission_Type = 0x1;	/* 1 */
                    UNS16 TaskSlave_obj1803_Inhibit_Time = 0x40;	/* 64 */
                    UNS8 TaskSlave_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 TaskSlave_obj1803_Event_Timer = 0xA;	/* 10 */
                    UNS8 TaskSlave_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    subindex TaskSlave_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1803, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1803_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1803_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1803_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1803_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&TaskSlave_obj1803_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_obj1803_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 TaskSlave_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1A00[] = 
                    {
                      0x20000110,	/* 536871184 */
                      0x20000210,	/* 536871440 */
                      0x20000310,	/* 536871696 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TaskSlave_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A00[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A00[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A00[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A00[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A00[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A00[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A00[7], NULL }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 TaskSlave_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1A01[] = 
                    {
                      0x20010110,	/* 536936720 */
                      0x20010210,	/* 536936976 */
                      0x20010310,	/* 536937232 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TaskSlave_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A01[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A01[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A01[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A01[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A01[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A01[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A01[7], NULL }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 TaskSlave_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1A02[] = 
                    {
                      0x20030110,	/* 537067792 */
                      0x20030210,	/* 537068048 */
                      0x20030310,	/* 537068304 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TaskSlave_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A02[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A02[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A02[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A02[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A02[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A02[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A02[7], NULL }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 TaskSlave_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 TaskSlave_obj1A03[] = 
                    {
                      0x20040110,	/* 537133328 */
                      0x20040210,	/* 537133584 */
                      0x20040310,	/* 537133840 */
                      0x20040410,	/* 537134096 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex TaskSlave_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj1A03, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A03[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A03[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A03[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A03[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A03[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A03[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A03[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&TaskSlave_obj1A03[7], NULL }
                     };

/* index 0x2000 :   Mapped variable ACC */
                    UNS8 TaskSlave_highestSubIndex_obj2000 = 3; /* number of subindex - 1*/
                    subindex TaskSlave_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj2000, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&CAN_ACC[0], NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&CAN_ACC[1], NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&CAN_ACC[2], NULL }
                     };

/* index 0x2001 :   Mapped variable GYR */
                    UNS8 TaskSlave_highestSubIndex_obj2001 = 3; /* number of subindex - 1*/
                    subindex TaskSlave_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj2001, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&GYR[0], NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&GYR[1], NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&GYR[2], NULL }
                     };

/* index 0x2002 :   Mapped variable MAG */
                    UNS8 TaskSlave_highestSubIndex_obj2002 = 3; /* number of subindex - 1*/
                    subindex TaskSlave_Index2002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj2002, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MAG[0], NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MAG[1], NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&MAG[2], NULL }
                     };

/* index 0x2003 :   Mapped variable EUL */
                    UNS8 TaskSlave_highestSubIndex_obj2003 = 3; /* number of subindex - 1*/
                    subindex TaskSlave_Index2003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj2003, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&EUL[0], NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&EUL[1], NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&EUL[2], NULL }
                     };

/* index 0x2004 :   Mapped variable QUAT */
                    UNS8 TaskSlave_highestSubIndex_obj2004 = 4; /* number of subindex - 1*/
                    subindex TaskSlave_Index2004[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&TaskSlave_highestSubIndex_obj2004, NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&QUAT[0], NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&QUAT[1], NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&QUAT[2], NULL },
                       { RO, int16, sizeof (INTEGER16), (void*)&QUAT[3], NULL }
                     };

/* index 0x2100 :   Mapped variable CAN_BAUD */
                    subindex TaskSlave_Index2100[] = 
                     {
                       { RW|TO_BE_SAVE, int32, sizeof (INTEGER32), (void*)&CAN_BAUD, NULL }
                     };

/* index 0x2101 :   Mapped variable NodeID */
                    subindex TaskSlave_Index2101[] = 
                     {
                       { RW|TO_BE_SAVE, int32, sizeof (INTEGER32), (void*)&NodeID, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable TaskSlave_objdict[] = 
{
  { (subindex*)TaskSlave_Index1000,sizeof(TaskSlave_Index1000)/sizeof(TaskSlave_Index1000[0]), 0x1000},
  { (subindex*)TaskSlave_Index1001,sizeof(TaskSlave_Index1001)/sizeof(TaskSlave_Index1001[0]), 0x1001},
  { (subindex*)TaskSlave_Index1002,sizeof(TaskSlave_Index1002)/sizeof(TaskSlave_Index1002[0]), 0x1002},
  { (subindex*)TaskSlave_Index1005,sizeof(TaskSlave_Index1005)/sizeof(TaskSlave_Index1005[0]), 0x1005},
  { (subindex*)TaskSlave_Index1016,sizeof(TaskSlave_Index1016)/sizeof(TaskSlave_Index1016[0]), 0x1016},
  { (subindex*)TaskSlave_Index1017,sizeof(TaskSlave_Index1017)/sizeof(TaskSlave_Index1017[0]), 0x1017},
  { (subindex*)TaskSlave_Index1018,sizeof(TaskSlave_Index1018)/sizeof(TaskSlave_Index1018[0]), 0x1018},
  { (subindex*)TaskSlave_Index1200,sizeof(TaskSlave_Index1200)/sizeof(TaskSlave_Index1200[0]), 0x1200},
  { (subindex*)TaskSlave_Index1400,sizeof(TaskSlave_Index1400)/sizeof(TaskSlave_Index1400[0]), 0x1400},
  { (subindex*)TaskSlave_Index1401,sizeof(TaskSlave_Index1401)/sizeof(TaskSlave_Index1401[0]), 0x1401},
  { (subindex*)TaskSlave_Index1402,sizeof(TaskSlave_Index1402)/sizeof(TaskSlave_Index1402[0]), 0x1402},
  { (subindex*)TaskSlave_Index1403,sizeof(TaskSlave_Index1403)/sizeof(TaskSlave_Index1403[0]), 0x1403},
  { (subindex*)TaskSlave_Index1600,sizeof(TaskSlave_Index1600)/sizeof(TaskSlave_Index1600[0]), 0x1600},
  { (subindex*)TaskSlave_Index1601,sizeof(TaskSlave_Index1601)/sizeof(TaskSlave_Index1601[0]), 0x1601},
  { (subindex*)TaskSlave_Index1602,sizeof(TaskSlave_Index1602)/sizeof(TaskSlave_Index1602[0]), 0x1602},
  { (subindex*)TaskSlave_Index1603,sizeof(TaskSlave_Index1603)/sizeof(TaskSlave_Index1603[0]), 0x1603},
  { (subindex*)TaskSlave_Index1800,sizeof(TaskSlave_Index1800)/sizeof(TaskSlave_Index1800[0]), 0x1800},
  { (subindex*)TaskSlave_Index1801,sizeof(TaskSlave_Index1801)/sizeof(TaskSlave_Index1801[0]), 0x1801},
  { (subindex*)TaskSlave_Index1802,sizeof(TaskSlave_Index1802)/sizeof(TaskSlave_Index1802[0]), 0x1802},
  { (subindex*)TaskSlave_Index1803,sizeof(TaskSlave_Index1803)/sizeof(TaskSlave_Index1803[0]), 0x1803},
  { (subindex*)TaskSlave_Index1A00,sizeof(TaskSlave_Index1A00)/sizeof(TaskSlave_Index1A00[0]), 0x1A00},
  { (subindex*)TaskSlave_Index1A01,sizeof(TaskSlave_Index1A01)/sizeof(TaskSlave_Index1A01[0]), 0x1A01},
  { (subindex*)TaskSlave_Index1A02,sizeof(TaskSlave_Index1A02)/sizeof(TaskSlave_Index1A02[0]), 0x1A02},
  { (subindex*)TaskSlave_Index1A03,sizeof(TaskSlave_Index1A03)/sizeof(TaskSlave_Index1A03[0]), 0x1A03},
  { (subindex*)TaskSlave_Index2000,sizeof(TaskSlave_Index2000)/sizeof(TaskSlave_Index2000[0]), 0x2000},
  { (subindex*)TaskSlave_Index2001,sizeof(TaskSlave_Index2001)/sizeof(TaskSlave_Index2001[0]), 0x2001},
  { (subindex*)TaskSlave_Index2002,sizeof(TaskSlave_Index2002)/sizeof(TaskSlave_Index2002[0]), 0x2002},
  { (subindex*)TaskSlave_Index2003,sizeof(TaskSlave_Index2003)/sizeof(TaskSlave_Index2003[0]), 0x2003},
  { (subindex*)TaskSlave_Index2004,sizeof(TaskSlave_Index2004)/sizeof(TaskSlave_Index2004[0]), 0x2004},
  { (subindex*)TaskSlave_Index2100,sizeof(TaskSlave_Index2100)/sizeof(TaskSlave_Index2100[0]), 0x2100},
  { (subindex*)TaskSlave_Index2101,sizeof(TaskSlave_Index2101)/sizeof(TaskSlave_Index2101[0]), 0x2101},
};

const indextable * TaskSlave_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1002: i = 2;break;
		case 0x1005: i = 3;break;
		case 0x1016: i = 4;break;
		case 0x1017: i = 5;break;
		case 0x1018: i = 6;break;
		case 0x1200: i = 7;break;
		case 0x1400: i = 8;break;
		case 0x1401: i = 9;break;
		case 0x1402: i = 10;break;
		case 0x1403: i = 11;break;
		case 0x1600: i = 12;break;
		case 0x1601: i = 13;break;
		case 0x1602: i = 14;break;
		case 0x1603: i = 15;break;
		case 0x1800: i = 16;break;
		case 0x1801: i = 17;break;
		case 0x1802: i = 18;break;
		case 0x1803: i = 19;break;
		case 0x1A00: i = 20;break;
		case 0x1A01: i = 21;break;
		case 0x1A02: i = 22;break;
		case 0x1A03: i = 23;break;
		case 0x2000: i = 24;break;
		case 0x2001: i = 25;break;
		case 0x2002: i = 26;break;
		case 0x2003: i = 27;break;
		case 0x2004: i = 28;break;
		case 0x2100: i = 29;break;
		case 0x2101: i = 30;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &TaskSlave_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status TaskSlave_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index TaskSlave_firstIndex = {
  7, /* SDO_SVR */
  0, /* SDO_CLT */
  8, /* PDO_RCV */
  12, /* PDO_RCV_MAP */
  16, /* PDO_TRS */
  20 /* PDO_TRS_MAP */
};

const quick_index TaskSlave_lastIndex = {
  7, /* SDO_SVR */
  0, /* SDO_CLT */
  11, /* PDO_RCV */
  15, /* PDO_RCV_MAP */
  19, /* PDO_TRS */
  23 /* PDO_TRS_MAP */
};

const UNS16 TaskSlave_ObjdictSize = sizeof(TaskSlave_objdict)/sizeof(TaskSlave_objdict[0]); 

CO_Data TaskSlave_Data = CANOPEN_NODE_DATA_INITIALIZER(TaskSlave);

