
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TASKSLAVE_H
#define TASKSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TaskSlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TaskSlave_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data TaskSlave_Data;
extern INTEGER16 CAN_ACC[3];		/* Mapped at index 0x2000, subindex 0x01 - 0x03 */
extern INTEGER16 GYR[3];		/* Mapped at index 0x2001, subindex 0x01 - 0x03 */
extern INTEGER16 MAG[3];		/* Mapped at index 0x2002, subindex 0x01 - 0x03 */
extern INTEGER16 EUL[3];		/* Mapped at index 0x2003, subindex 0x01 - 0x03 */
extern INTEGER16 QUAT[4];		/* Mapped at index 0x2004, subindex 0x01 - 0x04 */
extern INTEGER32 CAN_BAUD;		/* Mapped at index 0x2100, subindex 0x00*/
extern INTEGER32 NodeID;		/* Mapped at index 0x2101, subindex 0x00*/

#endif // TASKSLAVE_H
